"""empty message

Revision ID: 923b478902f7
Revises: a9cac6f7fb1e
Create Date: 2024-09-29 18:38:38.936335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923b478902f7'
down_revision = 'a9cac6f7fb1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=80), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
